dist: trusty
sudo: require


notifications:
  email: false
# add qt support
before_install:
    - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty
    - sudo apt-get -qq update
install:
    - sudo apt-get --yes install qt55base git
    - git clone https://github.com/g-truc/glm && sudo cp -r glm/glm /usr/include 
language : cpp

compiler:
  - gcc

script :
  - cd /home/travis/build/NCCA/NGL
  - cmake CMakeLists.txt
  - make -j 2
