dist: trusty
sudo: require


notifications:
  email: false
# add qt support
before_install:
    - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty
    - sudo apt-get -qq update
install:
    - sudo apt-get --yes install qt55base git
    - git clone https://github.com/g-truc/glm && cd glm && sudo cp -r glm /usr/include && cd
language : cpp

compiler:
  - gcc

script :
  - cd && cd NGL && cmake  -DQt5OpenGL_DIR="/opt/qt55/lib/cmake/Qt5OpenGL"  && make -j2

