dist: trusty
sudo: require


notifications:
  email: false
# add qt support
before_install:
    - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty
    - sudo apt-get -qq update
install:
    - sudo apt-get --yes install qt55base git xorg-dev
    - git clone https://github.com/g-truc/glm && sudo cp -r glm/glm /usr/include 
    - git clone https://github.com/glfw/glfw && mkdir build && cd build && cmake ../glfw && make -j2 && sudo make install
language : cpp

compiler:
  - gcc

script :
  - cd /home/travis/build/NCCA/NGL
  - cmake  -DQt5OpenGL_DIR="/opt/qt55/lib/cmake/Qt5OpenGL" CMakeLists.txt  && make -j2
