- os: linux
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-6 qt55base git xorg-dev gtest 
  env:
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"



notifications:
  email: false
# add qt support

before_install:
    - eval "${MATRIX_EVAL}"


#before_install:
#    - sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty
#    - sudo apt-get update -qq
#    # C++17
#    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#    - sudo apt-get update -qq


install:
    #- sudo apt-get --yes install qt55base git xorg-dev
    - git clone https://github.com/g-truc/glm && sudo cp -r glm/glm /usr/include 
    - git clone https://github.com/glfw/glfw && mkdir build && cd build && cmake ../glfw && make -j2 && sudo make install
    - git clone https://github.com/google/googletest && cd googletest && mkdir build && cd build && cmake .. && make -j2 && sudo make install
    
# C++17
#    - sudo apt-get install -qq g++-6
#    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
    

#language : cpp

#compiler:
#  - gcc
#  - clang

script :
  - cd /home/travis/build/NCCA/NGL
  - cmake  -DQt5OpenGL_DIR="/opt/qt55/lib/cmake/Qt5OpenGL" CMakeLists.txt  && make -j2
 