version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo '
      - run :
           name : Install tools
           command: 'sudo apt-get install -y cmake libglfw3-dev' #qtbase5-dev libgtest-dev libglfw3-dev libpython2.7-dev'

      - run :
          name : Install gtest
          command : 'git clone https://github.com/google/googletest && cd googletest && mkdir build && cd build && cmake -DBUILD_GMOCK=OFF .. && make -j2 && sudo make install'
      - run : 
          name : Install glfw
          command : 'git clone https://github.com/glfw/glfw && mkdir build && cd build && cmake -DGLFW_BUILD_DOCS=OFF -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF ../glfw && make -j2 && sudo make install'
      
      - run : 
          command : 'NGLDIR=/root/project/NGL && cd NGL && cmake CMakeLists.txt'