version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run :
           name : Install tools
           command: 'apt-get update && sudo apt-get install -y cmake libglfw3-dev qtbase5-dev libpython2.7-dev'
  #         command: 'sudo apt-get install -y cmake libglfw3-dev' #qtbase5-dev libgtest-dev libglfw3-dev libpython2.7-dev'

      - run :
          name : Install gtest
          command : 'git clone https://github.com/google/googletest && cd googletest && mkdir build && cd build && cmake -DBUILD_GMOCK=OFF .. && make -j2 && sudo make install'
      
      - run : 
          command : 'cd NGL && NGLDIR=/root/project/NGL/ cmake CMakeLists.txt'