version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run :
          name : Install g++
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install cmake
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run : 
          name : Get NGL
          command : 'pwd && git clone https://github.com:/NCCA/NGL && cd NGL && cmake CMakeLists'