version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run :
          name : Install g++
          command: 'apt-get update && apt-get install -y gcc g++ && apt-get install -y git'
      - run:
          name: Install cmake
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run : 
          command : 'cd NGL && cmake CMakeLists'